"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25 23:24:26.884202
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref", sa.String(length=20), nullable=False),
        sa.Column("service", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("company", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("pickup", sa.String(length=120), nullable=False),
        sa.Column("delivery", sa.String(length=120), nullable=False),
        sa.Column("from_hub", sa.String(length=40), nullable=False),
        sa.Column("to_hub", sa.String(length=40), nullable=False),
        sa.Column("km", sa.Integer(), nullable=False),
        sa.Column("cargo", sa.String(length=80), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("truck", sa.String(length=60), nullable=False),
        sa.Column("load_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("rate", sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("internal_notes", sa.Text(), nullable=False),
        sa.Column("load_ref", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotes")),
    )
    op.create_index(op.f("ix_quotes_ref"), "quotes", ["ref"], unique=True)
    op.create_index(op.f("ix_quotes_status"), "quotes", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "loads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref", sa.String(length=20), nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=True),
        sa.Column("customer", sa.String(length=120), nullable=False),
        sa.Column("customer_phone", sa.String(length=40), nullable=False),
        sa.Column("customer_email", sa.String(length=254), nullable=False),
        sa.Column("cargo", sa.String(length=120), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("truck_type", sa.String(length=60), nullable=False),
        sa.Column("truck_reg", sa.String(length=40), nullable=False),
        sa.Column("driver", sa.String(length=120), nullable=False),
        sa.Column("driver_phone", sa.String(length=40), nullable=False),
        sa.Column("load_date", sa.Date(), nullable=True),
        sa.Column("rate", sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("origin", sa.String(length=120), nullable=False),
        sa.Column("destination", sa.String(length=120), nullable=False),
        sa.Column("from_hub", sa.String(length=40), nullable=False),
        sa.Column("to_hub", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("at", sa.String(length=40), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=False),
        sa.Column("eta", sa.Date(), nullable=True),
        sa.Column("public_note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("fk_loads_quote_id_quotes"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loads")),
    )
    op.create_index(op.f("ix_loads_ref"), "loads", ["ref"], unique=True)
    op.create_index(op.f("ix_loads_status"), "loads", ["status"], unique=False)
    op.create_table(
        "load_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("at", sa.String(length=40), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["load_id"], ["loads.id"], name=op.f("fk_load_events_load_id_loads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_load_events")),
    )
    op.create_index(op.f("ix_load_events_load_id"), "load_events", ["load_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_load_events_load_id"), table_name="load_events")
    op.drop_table("load_events")
    op.drop_index(op.f("ix_loads_status"), table_name="loads")
    op.drop_index(op.f("ix_loads_ref"), table_name="loads")
    op.drop_table("loads")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_quotes_status"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_ref"), table_name="quotes")
    op.drop_table("quotes")
    # ### end Alembic commands ###
